include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true
  exclude:
    - lib/src/generated/**
    - example/**

linter:
  rules:
    avoid_print: true
    cancel_subscriptions: true
    close_sinks: true
